import type { Pack } from '@/lib/types'

export const PACKS: Pack[] = [
  {
    id: 'bronze',
    name: 'Bronze Pack',
    price: 0,
    cards: 3,
    minRating: 80,
    maxRating: 86,
    accent: '#cd7f32',
    description: 'Starter rated players. A solid first squad foundation.',
  },
  {
    id: 'silver',
    name: 'Silver Pack',
    price: 250,
    cards: 3,
    minRating: 84,
    maxRating: 89,
    accent: '#c0c0c8',
    description: 'Reliable mid-tier talent with rare upside.',
  },
  {
    id: 'gold',
    name: 'Gold Pack',
    price: 600,
    cards: 4,
    minRating: 86,
    maxRating: 91,
    accent: '#d4af37',
    description: 'Premium gold-tier players guaranteed.',
  },
  {
    id: 'premium',
    name: 'Premium Gold',
    price: 1200,
    cards: 5,
    minRating: 88,
    maxRating: 93,
    accent: '#f0d77b',
    description: 'Elevated odds for epics and heroes.',
  },
  {
    id: 'legend',
    name: 'Legend Pack',
    price: 2500,
    cards: 5,
    minRating: 89,
    maxRating: 94,
    accent: '#32ff9c',
    description: 'High chance at heroes and modern icons.',
  },
  {
    id: 'icon',
    name: 'Icon Pack',
    price: 5000,
    cards: 3,
    minRating: 90,
    maxRating: 95,
    accent: '#ffffff',
    description: 'Guaranteed icon-tier legend inside.',
  },
  {
    id: 'worldcup',
    name: 'World Cup Pack',
    price: 4000,
    cards: 5,
    minRating: 89,
    maxRating: 95,
    accent: '#32d0ff',
    description: 'National team legends from 1970–2026.',
  },
  {
    id: 'ultimate',
    name: 'Ultimate Pack',
    price: 9000,
    cards: 6,
    minRating: 91,
    maxRating: 99,
    accent: '#ff3da6',
    description: 'The best pack. Secret prime cards possible.',
  },
]
